jenkins:
  systemMessage: "Jenkins 中文社区"
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  disableRememberMe: false
  labelString: master
  mode: NORMAL
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  views:
  - all:
      name: "all"
  clouds:
  - kubernetes:
      name: kubernetes
      credentialsId: "c6369e96-009b-44fe-9090-c65eb6030334"
      jenkinsTunnel: ci.surenpi.com:50000
      jenkinsUrl: http://ci.surenpi.com
      maxRequestsPerHostStr: "32"
      namespace: default
      serverUrl: https://117.48.228.41:6443
      podRetention: never
      containerCapStr: ""
      skipTlsVerify: true
      templates:
      - name: golang-1.12
        label: golang-1.12
        podRetention: never
        nodeUsageMode: NORMAL
        instanceCapStr: "5"
        containers:
        - name: golang
          args: cat
          command: /bin/sh -c
          image: index.alauda.cn/alaudaorg/builder-go:1.12-ubuntu-v0.1.7
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          alwaysPullImage: false
          resourceLimitCpu: 1
          resourceLimitMemory: 2500M
          resourceRequestCpu: 500m
          resourceRequestMemory: 750M
          privileged: false
          ttyEnabled: true
      - name: hugo
        label: hugo
        podRetention: never
        nodeUsageMode: NORMAL
        instanceCapStr: "5"
        containers:
        - name: jnlp
          args: ${computer.jnlpmac} ${computer.name}
          image: docker.io/surenpi/hugo-jnlp-agent
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          alwaysPullImage: false
          resourceLimitCpu: 1
          resourceLimitMemory: 2500M
          resourceRequestCpu: 500m
          resourceRequestMemory: 750M
          privileged: false
          ttyEnabled: true
